// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexora.Data;

#nullable disable

namespace Nexora.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nexora.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-aaaa-bbbb-cccc-000000000001",
                            AccessFailedCount = 0,
                            Apellido = "Vendedor",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000001",
                            Email = "vendor1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nombre = "Demo",
                            NormalizedEmail = "VENDOR1@EXAMPLE.COM",
                            NormalizedUserName = "VENDOR1@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "vendor1@example.com"
                        });
                });

            modelBuilder.Entity("Nexora.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icono")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icono = "bi-phone",
                            Nombre = "Celulares"
                        },
                        new
                        {
                            Id = 2,
                            Icono = "bi-laptop",
                            Nombre = "Laptops"
                        },
                        new
                        {
                            Id = 3,
                            Icono = "bi-tablet",
                            Nombre = "Tablets"
                        },
                        new
                        {
                            Id = 4,
                            Icono = "bi-headphones",
                            Nombre = "Audio"
                        },
                        new
                        {
                            Id = 5,
                            Icono = "bi-controller",
                            Nombre = "Gaming"
                        },
                        new
                        {
                            Id = 6,
                            Icono = "bi-plug",
                            Nombre = "Accesorios"
                        });
                });

            modelBuilder.Entity("Nexora.Models.DetalleOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesOrden");
                });

            modelBuilder.Entity("Nexora.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DireccionEnvio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Nexora.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Especificaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GarantiaMeses")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("VendedorId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Especificaciones = "Producto iPhone 17 Pro Max de Apple.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=iPhone%2017%20Pro%20Max",
                            Marca = "Apple",
                            Modelo = "17 Pro Max",
                            Nombre = "iPhone 17 Pro Max",
                            Precio = 1499.99m,
                            Rating = 4.8m,
                            SKU = "IP17PM-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 1,
                            Especificaciones = "Producto Samsung Galaxy S26 Ultra de Samsung.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Samsung%20Galaxy%20S26%20Ultra",
                            Marca = "Samsung",
                            Modelo = "Galaxy S26 Ultra",
                            Nombre = "Samsung Galaxy S26 Ultra",
                            Precio = 1399.99m,
                            Rating = 4.8m,
                            SKU = "SS26U-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 1,
                            Especificaciones = "Producto Samsung Galaxy Fold 8 de Samsung.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Samsung%20Galaxy%20Fold%208",
                            Marca = "Samsung",
                            Modelo = "Galaxy Fold 8",
                            Nombre = "Samsung Galaxy Fold 8",
                            Precio = 1899.99m,
                            Rating = 4.8m,
                            SKU = "SFO8-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 1,
                            Especificaciones = "Producto iPhone 17 de Apple.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=iPhone%2017",
                            Marca = "Apple",
                            Modelo = "17",
                            Nombre = "iPhone 17",
                            Precio = 1099.99m,
                            Rating = 4.8m,
                            SKU = "IP17-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 1,
                            Especificaciones = "Producto Samsung Galaxy S26 de Samsung.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Samsung%20Galaxy%20S26",
                            Marca = "Samsung",
                            Modelo = "Galaxy S26",
                            Nombre = "Samsung Galaxy S26",
                            Precio = 899.99m,
                            Rating = 4.8m,
                            SKU = "SS26-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 1,
                            Especificaciones = "Producto Google Pixel 10 Pro de Google.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Google%20Pixel%2010%20Pro",
                            Marca = "Google",
                            Modelo = "Pixel 10 Pro",
                            Nombre = "Google Pixel 10 Pro",
                            Precio = 999.99m,
                            Rating = 4.8m,
                            SKU = "GP10P-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 1,
                            Especificaciones = "Producto Xiaomi 15 Ultra de Xiaomi.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Xiaomi%2015%20Ultra",
                            Marca = "Xiaomi",
                            Modelo = "15 Ultra",
                            Nombre = "Xiaomi 15 Ultra",
                            Precio = 849.99m,
                            Rating = 4.8m,
                            SKU = "X15U-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 1,
                            Especificaciones = "Producto Motorola Edge 60 de Motorola.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Motorola%20Edge%2060",
                            Marca = "Motorola",
                            Modelo = "Edge 60",
                            Nombre = "Motorola Edge 60",
                            Precio = 549.99m,
                            Rating = 4.8m,
                            SKU = "ME60-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaId = 2,
                            Especificaciones = "Producto MacBook Air M4 de Apple.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=MacBook%20Air%20M4",
                            Marca = "Apple",
                            Modelo = "Air M4",
                            Nombre = "MacBook Air M4",
                            Precio = 1199.99m,
                            Rating = 4.8m,
                            SKU = "MBA-M4-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaId = 2,
                            Especificaciones = "Producto MacBook Pro 16\" M4 Max de Apple.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=MacBook%20Pro%2016%22%20M4%20Max",
                            Marca = "Apple",
                            Modelo = "Pro 16 M4 Max",
                            Nombre = "MacBook Pro 16\" M4 Max",
                            Precio = 2899.99m,
                            Rating = 4.8m,
                            SKU = "MBP16-M4M-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CategoriaId = 2,
                            Especificaciones = "Producto Dell XPS 15 de Dell.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Dell%20XPS%2015",
                            Marca = "Dell",
                            Modelo = "XPS 15",
                            Nombre = "Dell XPS 15",
                            Precio = 1599.99m,
                            Rating = 4.8m,
                            SKU = "DXPS15-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CategoriaId = 2,
                            Especificaciones = "Producto Lenovo ThinkPad X1 Carbon de Lenovo.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Lenovo%20ThinkPad%20X1%20Carbon",
                            Marca = "Lenovo",
                            Modelo = "ThinkPad X1 Carbon",
                            Nombre = "Lenovo ThinkPad X1 Carbon",
                            Precio = 1749.99m,
                            Rating = 4.8m,
                            SKU = "TPX1C-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            CategoriaId = 2,
                            Especificaciones = "Producto ASUS ROG Zephyrus G16 de Asus.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=ASUS%20ROG%20Zephyrus%20G16",
                            Marca = "Asus",
                            Modelo = "ROG Zephyrus G16",
                            Nombre = "ASUS ROG Zephyrus G16",
                            Precio = 2199.99m,
                            Rating = 4.8m,
                            SKU = "ROGG16-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            CategoriaId = 2,
                            Especificaciones = "Producto HP Spectre x360 de HP.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=HP%20Spectre%20x360",
                            Marca = "HP",
                            Modelo = "Spectre x360",
                            Nombre = "HP Spectre x360",
                            Precio = 1449.99m,
                            Rating = 4.8m,
                            SKU = "HPSX360-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            CategoriaId = 3,
                            Especificaciones = "Producto iPad Pro 13\" M4 de Apple.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=iPad%20Pro%2013%22%20M4",
                            Marca = "Apple",
                            Modelo = "iPad Pro 13 M4",
                            Nombre = "iPad Pro 13\" M4",
                            Precio = 1299.99m,
                            Rating = 4.8m,
                            SKU = "IPADPRO13-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            CategoriaId = 3,
                            Especificaciones = "Producto iPad Air 11\" de Apple.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=iPad%20Air%2011%22",
                            Marca = "Apple",
                            Modelo = "iPad Air 11",
                            Nombre = "iPad Air 11\"",
                            Precio = 699.99m,
                            Rating = 4.8m,
                            SKU = "IPADAIR11-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            CategoriaId = 3,
                            Especificaciones = "Producto Samsung Galaxy Tab S10 Ultra de Samsung.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Samsung%20Galaxy%20Tab%20S10%20Ultra",
                            Marca = "Samsung",
                            Modelo = "Galaxy Tab S10 Ultra",
                            Nombre = "Samsung Galaxy Tab S10 Ultra",
                            Precio = 1199.99m,
                            Rating = 4.8m,
                            SKU = "SGTABS10U-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            CategoriaId = 3,
                            Especificaciones = "Producto Microsoft Surface Pro 11 de Microsoft.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Microsoft%20Surface%20Pro%2011",
                            Marca = "Microsoft",
                            Modelo = "Surface Pro 11",
                            Nombre = "Microsoft Surface Pro 11",
                            Precio = 1099.99m,
                            Rating = 4.8m,
                            SKU = "MSPRO11-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            CategoriaId = 3,
                            Especificaciones = "Producto Lenovo Tab P12 de Lenovo.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Lenovo%20Tab%20P12",
                            Marca = "Lenovo",
                            Modelo = "Tab P12",
                            Nombre = "Lenovo Tab P12",
                            Precio = 499.99m,
                            Rating = 4.8m,
                            SKU = "LTP12-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            CategoriaId = 4,
                            Especificaciones = "Producto AirPods Pro 3 de Apple.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=AirPods%20Pro%203",
                            Marca = "Apple",
                            Modelo = "Pro 3",
                            Nombre = "AirPods Pro 3",
                            Precio = 249.99m,
                            Rating = 4.8m,
                            SKU = "APPRO3-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            CategoriaId = 4,
                            Especificaciones = "Producto Sony WH-1000XM6 de Sony.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Sony%20WH-1000XM6",
                            Marca = "Sony",
                            Modelo = "WH-1000XM6",
                            Nombre = "Sony WH-1000XM6",
                            Precio = 399.99m,
                            Rating = 4.8m,
                            SKU = "SWH1000XM6-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            CategoriaId = 4,
                            Especificaciones = "Producto Bose QuietComfort Ultra de Bose.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Bose%20QuietComfort%20Ultra",
                            Marca = "Bose",
                            Modelo = "QuietComfort Ultra",
                            Nombre = "Bose QuietComfort Ultra",
                            Precio = 379.99m,
                            Rating = 4.8m,
                            SKU = "BQCULTRA-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            CategoriaId = 4,
                            Especificaciones = "Producto JBL Charge 6 de JBL.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=JBL%20Charge%206",
                            Marca = "JBL",
                            Modelo = "Charge 6",
                            Nombre = "JBL Charge 6",
                            Precio = 199.99m,
                            Rating = 4.8m,
                            SKU = "JBLCH6-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            CategoriaId = 4,
                            Especificaciones = "Producto Samsung Galaxy Buds 4 Pro de Samsung.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Samsung%20Galaxy%20Buds%204%20Pro",
                            Marca = "Samsung",
                            Modelo = "Galaxy Buds 4 Pro",
                            Nombre = "Samsung Galaxy Buds 4 Pro",
                            Precio = 229.99m,
                            Rating = 4.8m,
                            SKU = "SGBUDS4P-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            CategoriaId = 4,
                            Especificaciones = "Producto Sonos Era 300 de Sonos.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Sonos%20Era%20300",
                            Marca = "Sonos",
                            Modelo = "Era 300",
                            Nombre = "Sonos Era 300",
                            Precio = 449.99m,
                            Rating = 4.8m,
                            SKU = "SONOSERA300-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            CategoriaId = 5,
                            Especificaciones = "Producto PlayStation 5 Pro de Sony.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=PlayStation%205%20Pro",
                            Marca = "Sony",
                            Modelo = "PS5 Pro",
                            Nombre = "PlayStation 5 Pro",
                            Precio = 699.99m,
                            Rating = 4.8m,
                            SKU = "PS5PRO-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            CategoriaId = 5,
                            Especificaciones = "Producto Xbox Series X de Microsoft.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Xbox%20Series%20X",
                            Marca = "Microsoft",
                            Modelo = "Series X",
                            Nombre = "Xbox Series X",
                            Precio = 499.99m,
                            Rating = 4.8m,
                            SKU = "XBOXSX-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            CategoriaId = 5,
                            Especificaciones = "Producto Nintendo Switch 2 de Nintendo.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Nintendo%20Switch%202",
                            Marca = "Nintendo",
                            Modelo = "Switch 2",
                            Nombre = "Nintendo Switch 2",
                            Precio = 449.99m,
                            Rating = 4.8m,
                            SKU = "NSW2-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            CategoriaId = 5,
                            Especificaciones = "Producto Logitech G Pro X Superlight 2 de Logitech.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Logitech%20G%20Pro%20X%20Superlight%202",
                            Marca = "Logitech",
                            Modelo = "G Pro X Superlight 2",
                            Nombre = "Logitech G Pro X Superlight 2",
                            Precio = 159.99m,
                            Rating = 4.8m,
                            SKU = "LGPSL2-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            CategoriaId = 5,
                            Especificaciones = "Producto Razer BlackWidow V4 de Razer.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Razer%20BlackWidow%20V4",
                            Marca = "Razer",
                            Modelo = "BlackWidow V4",
                            Nombre = "Razer BlackWidow V4",
                            Precio = 189.99m,
                            Rating = 4.8m,
                            SKU = "RBWV4-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 31,
                            Activo = true,
                            CategoriaId = 5,
                            Especificaciones = "Producto ASUS ROG Ally X de Asus.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=ASUS%20ROG%20Ally%20X",
                            Marca = "Asus",
                            Modelo = "ROG Ally X",
                            Nombre = "ASUS ROG Ally X",
                            Precio = 799.99m,
                            Rating = 4.8m,
                            SKU = "ROGALLYX-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 32,
                            Activo = true,
                            CategoriaId = 6,
                            Especificaciones = "Producto Cargador MagSafe 2 en 1 de Apple.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Cargador%20MagSafe%202%20en%201",
                            Marca = "Apple",
                            Modelo = "MagSafe 2 en 1",
                            Nombre = "Cargador MagSafe 2 en 1",
                            Precio = 79.99m,
                            Rating = 4.8m,
                            SKU = "MAGSAFE21-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 33,
                            Activo = true,
                            CategoriaId = 6,
                            Especificaciones = "Producto Power bank Anker 20,000mAh de Anker.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Power%20bank%20Anker%2020%2C000mAh",
                            Marca = "Anker",
                            Modelo = "Power bank 20,000mAh",
                            Nombre = "Power bank Anker 20,000mAh",
                            Precio = 59.99m,
                            Rating = 4.8m,
                            SKU = "ANKPB20K-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 34,
                            Activo = true,
                            CategoriaId = 6,
                            Especificaciones = "Producto Funda protectora iPhone 17 Pro de Genérica.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Funda%20protectora%20iPhone%2017%20Pro",
                            Marca = "Genérica",
                            Modelo = "Funda iPhone 17 Pro",
                            Nombre = "Funda protectora iPhone 17 Pro",
                            Precio = 39.99m,
                            Rating = 4.8m,
                            SKU = "FUNDAIP17P-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 35,
                            Activo = true,
                            CategoriaId = 6,
                            Especificaciones = "Producto Mouse inalámbrico Logitech MX Master 4 de Logitech.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Mouse%20inal%C3%A1mbrico%20Logitech%20MX%20Master%204",
                            Marca = "Logitech",
                            Modelo = "MX Master 4",
                            Nombre = "Mouse inalámbrico Logitech MX Master 4",
                            Precio = 109.99m,
                            Rating = 4.8m,
                            SKU = "MXM4-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 36,
                            Activo = true,
                            CategoriaId = 6,
                            Especificaciones = "Producto Hub USB-C 7 en 1 de Genérica.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Hub%20USB-C%207%20en%201",
                            Marca = "Genérica",
                            Modelo = "Hub USB-C 7 en 1",
                            Nombre = "Hub USB-C 7 en 1",
                            Precio = 49.99m,
                            Rating = 4.8m,
                            SKU = "HUBUSBC7-001",
                            Stock = 10,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 37,
                            Activo = true,
                            CategoriaId = 6,
                            Especificaciones = "Producto Soporte ajustable para laptop de Genérica.",
                            GarantiaMeses = 24,
                            ImagenUrl = "https://via.placeholder.com/600x400?text=Soporte%20ajustable%20para%20laptop",
                            Marca = "Genérica",
                            Modelo = "Soporte para laptop",
                            Nombre = "Soporte ajustable para laptop",
                            Precio = 34.99m,
                            Rating = 4.8m,
                            SKU = "SOPLAP-001",
                            Stock = 10,
                            VendedorId = 1
                        });
                });

            modelBuilder.Entity("Nexora.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NombreTienda")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Vendedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            ApplicationUserId = "00000000-aaaa-bbbb-cccc-000000000001",
                            Descripcion = "Tienda de demostración con productos de ejemplo",
                            Logo = "/images/tienda-demo.png",
                            NombreTienda = "Tienda Demo"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Nexora.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Nexora.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexora.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Nexora.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexora.Models.DetalleOrden", b =>
                {
                    b.HasOne("Nexora.Models.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexora.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Nexora.Models.Orden", b =>
                {
                    b.HasOne("Nexora.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Nexora.Models.Producto", b =>
                {
                    b.HasOne("Nexora.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexora.Models.Vendedor", "Vendedor")
                        .WithMany("Productos")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Nexora.Models.Vendedor", b =>
                {
                    b.HasOne("Nexora.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Nexora.Models.Orden", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Nexora.Models.Vendedor", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
